// playgrounds/react-app/src/app/CraftRouter.tsx
import { useEffect, useState } from 'react'
import { useParams } from 'react-router'
import { CraftPage, getCraftInstance, useCraftUrlBuilder } from '@query-api/react'

export default function CraftRouter() {
  const { '*': params } = useParams()
  const uri = params !== '' ? params : '__home__'

  const { authToken } = getCraftInstance()
  const apiUrl = useCraftUrlBuilder('entries').uri(uri).buildUrl('one')
  const [data, setData] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (!apiUrl || !authToken) return

    setLoading(true)
    setError(null)

    fetch(apiUrl, {
      headers: {
        Authorization: `${authToken}`,
      },
    })
      .then(async (res) => {
        if (!res.ok) throw new Error(await res.text())
        return res.json()
      })
      .then(setData)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false))
  }, [apiUrl])

  return (
    <div>
      {loading && <div>Loading...</div>}
      {error && <div style={{ color: 'red' }}>{error}</div>}
      {data && <CraftPage content={data} />}
    </div>
  )
}

// playgrounds/vue-app/src/CraftRouter.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { useCraftUrlBuilder, CraftNotImplemented, useCraft, type Config } from '@query-api/vue'
import { useCraftFetch } from './composables/useCraftFetch'

import Home from './views/home.vue'
import News from './views/news.vue'
import Headline from './components/headline.vue'

const mapping: Config = {
  pages: {
    home: Home,
    'news:home': News,
  },
  components: {
    headline: Headline,
    imageText: CraftNotImplemented,
  },
}

const route = useRoute()
const { authToken } = useCraft()
const urlBuilder = useCraftUrlBuilder('entries')
const uri = computed(() => route.params.pathMatch || '__home__')
const queryUrl = computed(() => urlBuilder.uri(uri.value).buildUrl('one'))
const { data, loading, error } = useCraftFetch(queryUrl, authToken)
</script>

<template>
  <div v-if="loading">Loading…</div>
  <div v-else-if="error">Error: {{ error.message }}</div>
  <div v-else>
    <CraftPage :config="mapping" :content="data" />
  </div>
</template>
