// packages/react/src/components/CraftArea.tsx
import type { ContentMapping } from '../types'
import { getContentMapping } from '../composables/useApi'

function getCurrentComponent(cData: object, contentMapping: ContentMapping) {
  if (!contentMapping || !('components' in contentMapping)) {
    throw new Error(
      'Configuration is missing the "components" property or is invalid. Check your config object',
    )
  }

  if (!('type' in cData) || typeof cData.type !== 'string') {
    throw new Error('Provided data has no valid type set. Check your queried data.')
  }

  const ComponentEl = contentMapping.components[cData.type]

  if (!ComponentEl) {
    console.error(`No mapped component found for component type: ${cData.type}`)
  }

  return ComponentEl
}

type Props = {
  content: Array<object> | null
}

const CraftArea: React.FC<Props> = ({ content }) => {
  if (!content) return
  const contentMapping = getContentMapping()
  const elements: React.ReactNode[] = []

  for (let i = 0; i < content.length; i++) {
    const cData = content[i]
    const Component = getCurrentComponent(cData, contentMapping)
    if (!Component) continue
    elements.push(<Component key={i} {...cData} />)
  }

  return <div>{elements}</div>
}

export default CraftArea

// packages/vue/src/components/CraftArea.vue
<script lang="ts" setup>
import type { ContentMapping, CraftAreaComponent } from '../types'
import { inject } from 'vue'
import type { PropType } from 'vue'
const props = defineProps({
  content: {
    type: Array as PropType<unknown[]>,
    required: true,
  },
})

const config = inject<ContentMapping>('config')

function getCurrentComponent(component: unknown) {
  if (!config || !('components' in config)) {
    throw new Error('Configuration is missing components or invalid. Check your config object')
  }

  const typedComponent = component as CraftAreaComponent

  if (!('type' in typedComponent) || typeof typedComponent.type !== 'string') {
    throw new Error('Provided content has no valid type set. Check your queried data.')
  }

  const cName = typedComponent.type
  const componentEl = config.components[cName]

  if (!componentEl) {
    console.error(`No mapped component found for component type: ${cName}`)
  }

  return componentEl
}
</script>

<template>
  <div>
    <div v-for="(component, index) in props.content" :key="index">
      <component :is="getCurrentComponent(component)" v-bind="component as CraftAreaComponent" />
    </div>
  </div>
</template>
